# Generated by Django 2.0.7 on 2018-07-28 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('S', 'Starting Call'), ('E', 'End Call')], default='S', max_length=1, verbose_name='Record Type')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Record Timestamp')),
                ('call_id', models.IntegerField(verbose_name='Call ID')),
                ('source', models.CharField(max_length=9, verbose_name='Origin Phone Number')),
                ('destination', models.CharField(max_length=9, verbose_name='Destination Phone Number')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('call_id', 'record_type', 'source')},
        ),
    ]
