# Generated by Django 2.0.7 on 2018-09-09 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_charge', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Standing Charge')),
                ('minute_charge', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Minute Charge')),
                ('period', models.CharField(max_length=7, verbose_name='Period')),
                ('subscriber', models.CharField(max_length=9, verbose_name='Subscriber')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Total Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('S', 'Starting Call'), ('E', 'End Call')], default='S', max_length=1, verbose_name='Record Type')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Record Timestamp')),
                ('call_id', models.IntegerField(verbose_name='Call ID')),
                ('source', models.CharField(max_length=9, verbose_name='Origin Phone Number')),
                ('destination', models.CharField(max_length=9, verbose_name='Destination Phone Number')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='bills.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('S', 'Standing Charge'), ('M', 'Minute Charge')], default='S', max_length=1, verbose_name='Charge Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Charge Value')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('call_id', 'record_type', 'source')},
        ),
    ]
