# Generated by Django 2.0.7 on 2018-08-06 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_charge', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Standing Charge')),
                ('minute_charge', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Minute Charge')),
                ('period', models.CharField(max_length=7, verbose_name='Period')),
                ('subscriber', models.CharField(max_length=9, verbose_name='Subscriber')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Total Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Record Timestamp'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='bills.Bill'),
        ),
    ]
